// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsXqV2xQxFMvnRCHbb_F_iEbPugVkO4w',
    appId: '1:714456095150:web:6ea0fcde812d105b04d03f',
    messagingSenderId: '714456095150',
    projectId: 'signin-tes',
    authDomain: 'signin-tes.firebaseapp.com',
    storageBucket: 'signin-tes.appspot.com',
    measurementId: 'G-EXFLFE7M09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mPu4GJxTZ9zWNXENKxvVMJT17F7OMsM',
    appId: '1:714456095150:android:0ed526d94316390504d03f',
    messagingSenderId: '714456095150',
    projectId: 'signin-tes',
    storageBucket: 'signin-tes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9b4VxG3yPjAhohd6pBK6G6JtecafN4GI',
    appId: '1:714456095150:ios:25215d5b1aeb2c2604d03f',
    messagingSenderId: '714456095150',
    projectId: 'signin-tes',
    storageBucket: 'signin-tes.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9b4VxG3yPjAhohd6pBK6G6JtecafN4GI',
    appId: '1:714456095150:ios:f24e482da7253d7e04d03f',
    messagingSenderId: '714456095150',
    projectId: 'signin-tes',
    storageBucket: 'signin-tes.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
